package com.realnewsletter.service;

import com.realnewsletter.dto.ArticleDto;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.reactive.function.client.WebClient;
import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

import java.util.List;

/**
 * Service for fetching articles from the Newsdata.io API
 * (https://newsdata.io).
 */
@Service
public class ExternalNewsClient {

    private static final Logger logger = LoggerFactory.getLogger(ExternalNewsClient.class);

    private final WebClient webClient;

    @Value("${external.news.api.url:https://newsdata.io/api/1/news}")
    private String articlesApiUrl;

    @Value("${external.news.api.key:}")
    private String apiKey;

    public ExternalNewsClient(WebClient webClient) {
        this.webClient = webClient;
    }

    /**
     * Fetches the latest articles from the Newsdata.io API.
     *
     * <p>Query parameters:
     * <ul>
     *   <li>{@code apikey}   – Newsdata.io API key (lowercase 'k')</li>
     *   <li>{@code language} – filter to English articles</li>
     *   <li>{@code country}  – filter to US sources</li>
     * </ul>
     *
     * @return Flux of {@link ArticleDto}
     */
    public Flux<ArticleDto> fetchTrendingArticles() {
        return webClient.get()
            .uri(articlesApiUrl + "?apikey=" + apiKey + "&language=en&country=us")
            .retrieve()
            .onStatus(status -> !status.is2xxSuccessful(), response -> {
                logger.error("Error fetching articles from Newsdata.io: {}", response.statusCode());
                return Mono.error(new RuntimeException("Failed to fetch articles from Newsdata.io"));
            })
            .bodyToMono(NewsdataResponse.class)
            .flatMapMany(response -> Flux.fromIterable(response.results()))
            .take(2)  // Limit to 2 articles
            .map(article -> new ArticleDto(
                    null,                           // id (generated by DB)
                    article.article_id(),
                    article.link(),
                    article.title(),
                    article.description(),
                    article.content() != null ? article.content() : article.description(),
                    article.keywordsAsString(),
                    article.creatorAsString(),
                    article.language(),
                    article.countryAsString(),
                    article.categoryAsString(),
                    null,                           // datatype
                    null,                           // pubDate (will parse from string)
                    article.pubDateTZ(),
                    null,                           // fetchedAt (set by service)
                    article.image_url(),
                    article.video_url(),
                    article.source_id(),
                    article.source_name(),
                    article.source_priority(),
                    article.source_url(),
                    article.source_icon(),
                    article.sentiment(),
                    article.sentiment_stats(),
                    null,                           // aiTag
                    null,                           // aiRegion
                    null,                           // aiOrg
                    null,                           // aiSummary
                    false,                          // duplicate
                    null                            // createdAt
            ));
    }

    /**
     * Top-level Newsdata.io API response wrapper.
     * The {@code results} array contains the articles.
     */
    public record NewsdataResponse(String status, List<NewsdataArticle> results) {}

    /**
     * Newsdata.io API response to ArticleDto mapping.
     * Note: Some fields like keywords, creator, country, category are arrays in the API.
     */
    public record NewsdataArticle(
            String article_id,
            String title,
            String link,
            String description,
            String content,
            List<String> keywords,
            List<String> creator,
            String language,
            List<String> country,
            List<String> category,
            String image_url,
            String video_url,
            String pubDate,
            String pubDateTZ,
            String fetched_at,
            String source_id,
            String source_name,
            Integer source_priority,
            String source_url,
            String source_icon,
            String sentiment,
            String sentiment_stats
    ) {
        /**
         * Converts list to comma-separated string for storage
         */
        private String keywordsAsString() {
            return keywords != null ? String.join(",", keywords) : null;
        }

        /**
         * Converts list to comma-separated string for storage
         */
        private String creatorAsString() {
            return creator != null ? String.join(",", creator) : null;
        }

        /**
         * Converts list to comma-separated string for storage
         */
        private String countryAsString() {
            return country != null ? String.join(",", country) : null;
        }

        /**
         * Converts list to comma-separated string for storage
         */
        private String categoryAsString() {
            return category != null ? String.join(",", category) : null;
        }
    }
}
