-- Add AI-generated fields to articles table.
-- ai_summary holds a text summary generated by the AI model.
-- tags holds comma-separated tags generated by the AI model.
ALTER TABLE articles
    ADD COLUMN ai_summary TEXT,
    ADD COLUMN tags       TEXT;

